name: jengamate
description: JengaMate - Construction Materials Marketplace
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.10
  supabase_flutter: ^2.5.8
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.1.0
  flutter_stripe: ^10.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  pdf: ^3.10.7
  printing: ^5.12.0
  syncfusion_flutter_pdfviewer: ^24.2.9
  flutter_typeahead: ^5.0.2
  flutter_slidable: ^3.0.1
  badges: ^3.1.2
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  device_info_plus: ^9.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  firebase_crashlytics: ^3.4.9
  csv: ^5.1.1
  share_plus: ^7.2.2
  go_router: ^12.1.3
  universal_html: ^2.2.4
  fl_chart: ^0.66.1
  google_fonts: ^6.1.0
  video_player: ^2.8.1
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  retrofit_generator: ^8.1.0
  mockito: ^5.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/default_avatar.png"
