class AppRoutes {
  static const String login = '/login';
  static const String dashboard = '/dashboard';
  static const String engineerRegistration = '/engineer-registration';
  static const String rfqSubmission = '/rfq-submission/:productId/:productName';
  static const String inquirySubmission = '/inquiry-submission';
  static const String adminTools = '/admin-tools';
  static const String addEditProduct = '/add-edit-product';
  static const String profile = '/profile';
  static const String products = '/products';
  static const String settings = '/settings';
  static const String help = '/help';
  static const String changePassword = '/change-password';
  static const String security = '/security';
  static const String identityVerification = '/identity-verification';
  static const String prioritySupport = '/priority-support';
  static const String chatList = '/chat-list';
  static const String notifications = '/notifications';
  static const String analytics = '/analytics';
  static const String categories = '/categories';
  static const String newInquiry = '/new-inquiry';
  static const String passwordReset = '/password-reset';
  static const String phoneRegistration = '/phone-registration';
  static const String otpVerification = '/otp-verification/:verificationId';
  static const String approvalPending = '/approval-pending';
  static const String inquiries = '/inquiries';
  static const String rfqList = '/rfq-list';
  static const String rfqManagement = '/rfq-management';
  static const String rfqDetails = '/rfq/:rfqId';
  static const String chatConversation = '/chat/:chatId';
  static const String commission = '/commission';
  static const String commissionTiers = '/commission-tiers';
  static const String withdrawals = '/withdrawals';
  static const String imageUploadTest = '/image-upload-test';
  static const String userDetails = 'user-details';
  static const String auditLog = 'audit-log';
  static const String invoices = '/invoices';
  static const String createInvoice = '/create-invoice';
  static const String invoiceDetails = '/invoice/:invoiceId';
  static const String orders = '/orders';
  static const String orderDetails = '/order/:orderId';
  static const String authTest = '/auth-test'; // Added auth test route
  static const String testSupabase = '/test-supabase'; // Supabase connection test
  
  // Admin routes
  static const String financialOversight = '/financial-oversight';
  static const String userManagement = '/user-management';
  static const String referralManagement = '/referral-management';
  static const String rfqManagementDashboard = '/rfq-management-dashboard';
  static const String rfqAnalyticsDashboard = '/rfq-analytics-dashboard';
  static const String financialDashboard = '/financial-dashboard';
  static const String systemSettings = '/system-settings';
  static const String advancedAnalytics = '/advanced-analytics';
  static const String enhancedAuditLogs = '/enhanced-audit-logs';
  static const String commissionTierManagement = '/commission-tier-management';
  static const String contentModeration = '/content-moderation';
  static const String adminSupport = '/admin-support';
}