// Mocks generated by Mockito 5.4.6 from annotations
// in jengamate/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i28;

import 'package:cloud_firestore/cloud_firestore.dart' as _i24;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:jengamate/models/audit_log_model.dart' as _i20;
import 'package:jengamate/models/category_model.dart' as _i14;
import 'package:jengamate/models/chat_message_model.dart' as _i27;
import 'package:jengamate/models/chat_room_model.dart' as _i21;
import 'package:jengamate/models/commission_model.dart' as _i13;
import 'package:jengamate/models/commission_tier_model.dart' as _i18;
import 'package:jengamate/models/content_report_model.dart' as _i19;
import 'package:jengamate/models/faq_model.dart' as _i25;
import 'package:jengamate/models/financial_transaction_model.dart' as _i17;
import 'package:jengamate/models/inquiry.dart' as _i26;
import 'package:jengamate/models/notification_model.dart' as _i9;
import 'package:jengamate/models/order_model.dart' as _i6;
import 'package:jengamate/models/payment_model.dart' as _i7;
import 'package:jengamate/models/product_model.dart' as _i15;
import 'package:jengamate/models/quote_model.dart' as _i12;
import 'package:jengamate/models/rfq_model.dart' as _i11;
import 'package:jengamate/models/support_ticket_model.dart' as _i22;
import 'package:jengamate/models/system_config_model.dart' as _i23;
import 'package:jengamate/models/user_model.dart' as _i10;
import 'package:jengamate/models/withdrawal_model.dart' as _i16;
import 'package:jengamate/services/auth_service.dart' as _i3;
import 'package:jengamate/services/database_service.dart' as _i8;
import 'package:jengamate/services/order_service.dart' as _i5;
import 'package:jengamate/services/payment_service.dart' as _i29;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i30;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i2.User?>.empty(),
      ) as _i4.Stream<_i2.User?>);

  @override
  _i4.Stream<Map<String, dynamic>?> get customClaimsStream =>
      (super.noSuchMethod(
        Invocation.getter(#customClaimsStream),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Stream<String?> get roleStream => (super.noSuchMethod(
        Invocation.getter(#roleStream),
        returnValue: _i4.Stream<String?>.empty(),
      ) as _i4.Stream<String?>);

  @override
  _i4.Future<_i2.UserCredential> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> registerWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #registerWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<void> sendOTP(
    String? phoneNumber,
    dynamic Function(String)? onCodeSent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOTP,
          [
            phoneNumber,
            onCodeSent,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserCredential?> verifyOTP(
    String? verificationId,
    String? smsCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            verificationId,
            smsCode,
          ],
        ),
        returnValue: _i4.Future<_i2.UserCredential?>.value(),
      ) as _i4.Future<_i2.UserCredential?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> reauthenticateWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> getCustomClaims() => (super.noSuchMethod(
        Invocation.method(
          #getCustomClaims,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<String?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isSupplier() => (super.noSuchMethod(
        Invocation.method(
          #isSupplier,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isApproved() => (super.noSuchMethod(
        Invocation.method(
          #isApproved,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasStorageAccess() => (super.noSuchMethod(
        Invocation.method(
          #hasStorageAccess,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i5.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i6.OrderModel>> getBuyerOrders(String? buyerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuyerOrders,
          [buyerId],
        ),
        returnValue: _i4.Stream<List<_i6.OrderModel>>.empty(),
      ) as _i4.Stream<List<_i6.OrderModel>>);

  @override
  _i4.Stream<List<_i6.OrderModel>> getSupplierOrders(String? supplierId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupplierOrders,
          [supplierId],
        ),
        returnValue: _i4.Stream<List<_i6.OrderModel>>.empty(),
      ) as _i4.Stream<List<_i6.OrderModel>>);

  @override
  _i4.Stream<_i6.OrderModel> getOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i4.Stream<_i6.OrderModel>.empty(),
      ) as _i4.Stream<_i6.OrderModel>);

  @override
  _i4.Future<_i6.OrderModel?> getOrderById(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderById,
          [orderId],
        ),
        returnValue: _i4.Future<_i6.OrderModel?>.value(),
      ) as _i4.Future<_i6.OrderModel?>);

  @override
  _i4.Stream<List<_i6.OrderModel>> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue: _i4.Stream<List<_i6.OrderModel>>.empty(),
      ) as _i4.Stream<List<_i6.OrderModel>>);

  @override
  _i4.Future<void> createOrder(_i6.OrderModel? order) => (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [order],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateOrder(_i6.OrderModel? order) => (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [order],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateOrderStatus(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            orderId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i7.PaymentModel>> streamOrderPayments(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamOrderPayments,
          [orderId],
        ),
        returnValue: _i4.Stream<List<_i7.PaymentModel>>.empty(),
      ) as _i4.Stream<List<_i7.PaymentModel>>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i8.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createNotification(_i9.NotificationModel? notification) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotification,
          [notification],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i9.NotificationModel>> streamUserNotifications(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamUserNotifications,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i9.NotificationModel>>.empty(),
      ) as _i4.Stream<List<_i9.NotificationModel>>);

  @override
  _i4.Stream<int> streamUnreadNotificationsCount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamUnreadNotificationsCount,
          [userId],
        ),
        returnValue: _i4.Stream<int>.empty(),
      ) as _i4.Stream<int>);

  @override
  _i4.Future<_i10.UserModel?> getUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [uid],
        ),
        returnValue: _i4.Future<_i10.UserModel?>.value(),
      ) as _i4.Future<_i10.UserModel?>);

  @override
  _i4.Future<void> updateUser(_i10.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i10.UserModel>> streamEnhancedUsers() => (super.noSuchMethod(
        Invocation.method(
          #streamEnhancedUsers,
          [],
        ),
        returnValue: _i4.Stream<List<_i10.UserModel>>.empty(),
      ) as _i4.Stream<List<_i10.UserModel>>);

  @override
  _i4.Stream<List<_i10.UserModel>> streamAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #streamAllUsers,
          [],
        ),
        returnValue: _i4.Stream<List<_i10.UserModel>>.empty(),
      ) as _i4.Stream<List<_i10.UserModel>>);

  @override
  _i4.Future<List<_i10.UserModel>> getUsersCreatedAfter(DateTime? startDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersCreatedAfter,
          [startDate],
        ),
        returnValue: _i4.Future<List<_i10.UserModel>>.value(<_i10.UserModel>[]),
      ) as _i4.Future<List<_i10.UserModel>>);

  @override
  _i4.Stream<List<_i11.RFQModel>> streamAllRFQs() => (super.noSuchMethod(
        Invocation.method(
          #streamAllRFQs,
          [],
        ),
        returnValue: _i4.Stream<List<_i11.RFQModel>>.empty(),
      ) as _i4.Stream<List<_i11.RFQModel>>);

  @override
  _i4.Stream<List<_i11.RFQModel>> streamUserRFQs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamUserRFQs,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i11.RFQModel>>.empty(),
      ) as _i4.Stream<List<_i11.RFQModel>>);

  @override
  _i4.Stream<List<_i11.RFQModel>> streamInquiries(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamInquiries,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i11.RFQModel>>.empty(),
      ) as _i4.Stream<List<_i11.RFQModel>>);

  @override
  _i4.Future<_i11.RFQModel?> getRFQ(String? rfqId) => (super.noSuchMethod(
        Invocation.method(
          #getRFQ,
          [rfqId],
        ),
        returnValue: _i4.Future<_i11.RFQModel?>.value(),
      ) as _i4.Future<_i11.RFQModel?>);

  @override
  _i4.Future<void> updateRFQStatus(
    String? rfqId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRFQStatus,
          [
            rfqId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createQuote(_i12.QuoteModel? quote) => (super.noSuchMethod(
        Invocation.method(
          #createQuote,
          [quote],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i12.QuoteModel>> streamQuotesForRFQ(String? rfqId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamQuotesForRFQ,
          [rfqId],
        ),
        returnValue: _i4.Stream<List<_i12.QuoteModel>>.empty(),
      ) as _i4.Stream<List<_i12.QuoteModel>>);

  @override
  _i4.Stream<List<_i13.CommissionModel>> getAllCommissions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCommissions,
          [],
        ),
        returnValue: _i4.Stream<List<_i13.CommissionModel>>.empty(),
      ) as _i4.Stream<List<_i13.CommissionModel>>);

  @override
  _i4.Stream<List<_i13.CommissionModel>> streamUserCommissions(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamUserCommissions,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i13.CommissionModel>>.empty(),
      ) as _i4.Stream<List<_i13.CommissionModel>>);

  @override
  _i4.Future<List<_i13.CommissionModel>> getCommissionRules() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommissionRules,
          [],
        ),
        returnValue: _i4.Future<List<_i13.CommissionModel>>.value(
            <_i13.CommissionModel>[]),
      ) as _i4.Future<List<_i13.CommissionModel>>);

  @override
  _i4.Stream<List<_i13.CommissionModel>> streamCommissionRules() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCommissionRules,
          [],
        ),
        returnValue: _i4.Stream<List<_i13.CommissionModel>>.empty(),
      ) as _i4.Stream<List<_i13.CommissionModel>>);

  @override
  _i4.Future<void> deleteCommissionRecord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCommissionRecord,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i13.CommissionModel>> streamTrashedCommissions() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamTrashedCommissions,
          [],
        ),
        returnValue: _i4.Stream<List<_i13.CommissionModel>>.empty(),
      ) as _i4.Stream<List<_i13.CommissionModel>>);

  @override
  _i4.Stream<List<_i14.CategoryModel>> streamCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCategories,
          [],
        ),
        returnValue: _i4.Stream<List<_i14.CategoryModel>>.empty(),
      ) as _i4.Stream<List<_i14.CategoryModel>>);

  @override
  _i4.Future<List<_i14.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i14.CategoryModel>>.value(<_i14.CategoryModel>[]),
      ) as _i4.Future<List<_i14.CategoryModel>>);

  @override
  _i4.Future<List<_i14.CategoryModel>> getSubCategories(String? parentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubCategories,
          [parentId],
        ),
        returnValue:
            _i4.Future<List<_i14.CategoryModel>>.value(<_i14.CategoryModel>[]),
      ) as _i4.Future<List<_i14.CategoryModel>>);

  @override
  _i4.Future<void> addCategory(_i14.CategoryModel? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCategory(_i14.CategoryModel? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i15.ProductModel>> streamProducts() => (super.noSuchMethod(
        Invocation.method(
          #streamProducts,
          [],
        ),
        returnValue: _i4.Stream<List<_i15.ProductModel>>.empty(),
      ) as _i4.Stream<List<_i15.ProductModel>>);

  @override
  _i4.Future<List<_i15.ProductModel>> getTopSellingProducts(int? limit) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopSellingProducts,
          [limit],
        ),
        returnValue:
            _i4.Future<List<_i15.ProductModel>>.value(<_i15.ProductModel>[]),
      ) as _i4.Future<List<_i15.ProductModel>>);

  @override
  _i4.Future<void> deleteProducts(List<String>? productIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProducts,
          [productIds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getProductImage(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #getProductImage,
          [productId],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Stream<List<_i16.WithdrawalModel>> streamWithdrawals(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamWithdrawals,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i16.WithdrawalModel>>.empty(),
      ) as _i4.Stream<List<_i16.WithdrawalModel>>);

  @override
  _i4.Future<void> updateWithdrawalStatus(
    String? withdrawalId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWithdrawalStatus,
          [
            withdrawalId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getAdminAnalytics() => (super.noSuchMethod(
        Invocation.method(
          #getAdminAnalytics,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getWithdrawalStats() => (super.noSuchMethod(
        Invocation.method(
          #getWithdrawalStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSalesOverTime() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesOverTime,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, int>> getOrderCountsByStatus() => (super.noSuchMethod(
        Invocation.method(
          #getOrderCountsByStatus,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUserGrowthOverTime() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGrowthOverTime,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Stream<List<_i17.FinancialTransactionModel>> getFinancialTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFinancialTransactions,
          [],
        ),
        returnValue: _i4.Stream<List<_i17.FinancialTransactionModel>>.empty(),
      ) as _i4.Stream<List<_i17.FinancialTransactionModel>>);

  @override
  _i4.Future<List<_i18.CommissionTier>> getCommissionTiers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommissionTiers,
          [],
        ),
        returnValue: _i4.Future<List<_i18.CommissionTier>>.value(
            <_i18.CommissionTier>[]),
      ) as _i4.Future<List<_i18.CommissionTier>>);

  @override
  _i4.Future<List<_i10.UserModel>> getUsersWithTierInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersWithTierInfo,
          [],
        ),
        returnValue: _i4.Future<List<_i10.UserModel>>.value(<_i10.UserModel>[]),
      ) as _i4.Future<List<_i10.UserModel>>);

  @override
  _i4.Future<List<_i19.ContentReport>> getContentReports({String? status}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentReports,
          [],
          {#status: status},
        ),
        returnValue:
            _i4.Future<List<_i19.ContentReport>>.value(<_i19.ContentReport>[]),
      ) as _i4.Future<List<_i19.ContentReport>>);

  @override
  _i4.Future<List<_i20.AuditLogModel>> getAuditLogs() => (super.noSuchMethod(
        Invocation.method(
          #getAuditLogs,
          [],
        ),
        returnValue:
            _i4.Future<List<_i20.AuditLogModel>>.value(<_i20.AuditLogModel>[]),
      ) as _i4.Future<List<_i20.AuditLogModel>>);

  @override
  _i4.Future<void> createAuditLog(_i20.AuditLogModel? log) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAuditLog,
          [log],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i21.ChatRoom>> streamChatRoomsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamChatRoomsForUser,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i21.ChatRoom>>.empty(),
      ) as _i4.Stream<List<_i21.ChatRoom>>);

  @override
  _i4.Future<List<_i22.SupportTicket>> getAllSupportTickets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSupportTickets,
          [],
        ),
        returnValue:
            _i4.Future<List<_i22.SupportTicket>>.value(<_i22.SupportTicket>[]),
      ) as _i4.Future<List<_i22.SupportTicket>>);

  @override
  _i4.Future<_i23.SystemConfig?> getSystemConfig() => (super.noSuchMethod(
        Invocation.method(
          #getSystemConfig,
          [],
        ),
        returnValue: _i4.Future<_i23.SystemConfig?>.value(),
      ) as _i4.Future<_i23.SystemConfig?>);

  @override
  _i4.Future<void> updateSystemConfig(_i23.SystemConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSystemConfig,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i17.FinancialTransactionModel>>
      getPaginatedFinancialTransactions({
    int? limit = 20,
    _i24.DocumentSnapshot<Object?>? startAfter,
    String? userId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getPaginatedFinancialTransactions,
              [],
              {
                #limit: limit,
                #startAfter: startAfter,
                #userId: userId,
              },
            ),
            returnValue: _i4.Future<List<_i17.FinancialTransactionModel>>.value(
                <_i17.FinancialTransactionModel>[]),
          ) as _i4.Future<List<_i17.FinancialTransactionModel>>);

  @override
  _i4.Future<_i24.DocumentSnapshot<Object?>?> getLastTransactionDocument() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastTransactionDocument,
          [],
        ),
        returnValue: _i4.Future<_i24.DocumentSnapshot<Object?>?>.value(),
      ) as _i4.Future<_i24.DocumentSnapshot<Object?>?>);

  @override
  _i4.Future<List<_i22.SupportTicket>> getUserSupportTickets(
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSupportTickets,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<List<_i22.SupportTicket>>.value(<_i22.SupportTicket>[]),
      ) as _i4.Future<List<_i22.SupportTicket>>);

  @override
  _i4.Future<void> createSupportTicket(_i22.SupportTicket? ticket) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSupportTicket,
          [ticket],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i25.FAQItem>> getFAQs({String? category}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFAQs,
          [],
          {#category: category},
        ),
        returnValue: _i4.Future<List<_i25.FAQItem>>.value(<_i25.FAQItem>[]),
      ) as _i4.Future<List<_i25.FAQItem>>);

  @override
  _i4.Future<void> createFAQ(_i25.FAQItem? faq) => (super.noSuchMethod(
        Invocation.method(
          #createFAQ,
          [faq],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> requestWithdrawal(Map<String, dynamic>? withdrawal) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestWithdrawal,
          [withdrawal],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addOrUpdateProduct(Map<String, dynamic>? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdateProduct,
          [product],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addOrUpdateProductModel(_i15.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdateProductModel,
          [product],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i15.ProductModel?> getProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [productId],
        ),
        returnValue: _i4.Future<_i15.ProductModel?>.value(),
      ) as _i4.Future<_i15.ProductModel?>);

  @override
  _i4.Future<List<_i15.ProductModel>> getProductsByIds(
          List<String>? productIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByIds,
          [productIds],
        ),
        returnValue:
            _i4.Future<List<_i15.ProductModel>>.value(<_i15.ProductModel>[]),
      ) as _i4.Future<List<_i15.ProductModel>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getApprovedSuppliers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getApprovedSuppliers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> createRFQ(Map<String, dynamic>? rfq) => (super.noSuchMethod(
        Invocation.method(
          #createRFQ,
          [rfq],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRFQ(_i11.RFQModel? rfq) => (super.noSuchMethod(
        Invocation.method(
          #addRFQ,
          [rfq],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchUsers(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> updateCommissionRules(Map<String, dynamic>? rules) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCommissionRules,
          [rules],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<Map<String, dynamic>> streamOrderStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamOrderStats,
          [userId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<List<_i26.Inquiry>> streamInquiriesForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamInquiriesForUser,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i26.Inquiry>>.empty(),
      ) as _i4.Stream<List<_i26.Inquiry>>);

  @override
  _i4.Future<void> createInquiry(_i26.Inquiry? Inquiry) => (super.noSuchMethod(
        Invocation.method(
          #createInquiry,
          [Inquiry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addMessage(_i27.ChatMessage? message) => (super.noSuchMethod(
        Invocation.method(
          #addMessage,
          [message],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i27.ChatMessage>> streamMessages(String? chatRoomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamMessages,
          [chatRoomId],
        ),
        returnValue: _i4.Stream<List<_i27.ChatMessage>>.empty(),
      ) as _i4.Stream<List<_i27.ChatMessage>>);

  @override
  _i4.Future<_i21.ChatRoom?> getChatRoom(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #getChatRoom,
          [roomId],
        ),
        returnValue: _i4.Future<_i21.ChatRoom?>.value(),
      ) as _i4.Future<_i21.ChatRoom?>);

  @override
  _i4.Future<void> createChatRoom(_i21.ChatRoom? room) => (super.noSuchMethod(
        Invocation.method(
          #createChatRoom,
          [room],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createCommissionTier(_i18.CommissionTier? tier) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCommissionTier,
          [tier],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createContentReport(_i19.ContentReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #createContentReport,
          [report],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRank(Map<String, dynamic>? rank) => (super.noSuchMethod(
        Invocation.method(
          #addRank,
          [rank],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRank(Map<String, dynamic>? rank) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRank,
          [rank],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRank(String? rankId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRank,
          [rankId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<dynamic>> streamRanks() => (super.noSuchMethod(
        Invocation.method(
          #streamRanks,
          [],
        ),
        returnValue: _i4.Stream<List<dynamic>>.empty(),
      ) as _i4.Stream<List<dynamic>>);

  @override
  _i4.Future<void> addReview(Map<String, dynamic>? review) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReview,
          [review],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateModerationStatus(
    String? itemId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModerationStatus,
          [
            itemId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEnhancedUser(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEnhancedUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i9.NotificationModel>> getNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue: _i4.Stream<List<_i9.NotificationModel>>.empty(),
      ) as _i4.Stream<List<_i9.NotificationModel>>);

  @override
  _i4.Future<void> sendQuoteSubmissionNotification(
          Map<String, dynamic>? quote) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendQuoteSubmissionNotification,
          [quote],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i20.AuditLogModel>> getAuditLogsStream({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditLogsStream,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<List<_i20.AuditLogModel>>.empty(),
      ) as _i4.Stream<List<_i20.AuditLogModel>>);

  @override
  _i4.Future<Map<DateTime, double>> getSalesOverTimeMap() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesOverTimeMap,
          [],
        ),
        returnValue:
            _i4.Future<Map<DateTime, double>>.value(<DateTime, double>{}),
      ) as _i4.Future<Map<DateTime, double>>);

  @override
  _i4.Future<_i6.OrderModel?> getOrderByID(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderByID,
          [orderId],
        ),
        returnValue: _i4.Future<_i6.OrderModel?>.value(),
      ) as _i4.Future<_i6.OrderModel?>);

  @override
  _i4.Future<String?> uploadFile(
    _i28.Uint8List? bytes,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            bytes,
            path,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> addCommissionRecordValidated(
          _i13.CommissionModel? commission) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCommissionRecordValidated,
          [commission],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCommissionRecord(
    String? commissionId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCommissionRecord,
          [
            commissionId,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i26.Inquiry>> streamAllInquiries() => (super.noSuchMethod(
        Invocation.method(
          #streamAllInquiries,
          [],
        ),
        returnValue: _i4.Stream<List<_i26.Inquiry>>.empty(),
      ) as _i4.Stream<List<_i26.Inquiry>>);

  @override
  _i4.Future<_i10.UserModel?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i10.UserModel?>.value(),
      ) as _i4.Future<_i10.UserModel?>);

  @override
  _i4.Future<void> addInquiry(_i26.Inquiry? inquiry) => (super.noSuchMethod(
        Invocation.method(
          #addInquiry,
          [inquiry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUserReferrals(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserReferrals,
          [userId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<_i10.UserModel>> getUsersByIds(List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersByIds,
          [userIds],
        ),
        returnValue: _i4.Future<List<_i10.UserModel>>.value(<_i10.UserModel>[]),
      ) as _i4.Future<List<_i10.UserModel>>);

  @override
  _i4.Future<String?> uploadIdentityDocumentBytes(
    _i28.Uint8List? bytes,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadIdentityDocumentBytes,
          [
            bytes,
            userId,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> updateUserData(
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserData,
          [
            uid,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i12.QuoteModel>> streamQuotes(String? rfqId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamQuotes,
          [rfqId],
        ),
        returnValue: _i4.Stream<List<_i12.QuoteModel>>.empty(),
      ) as _i4.Stream<List<_i12.QuoteModel>>);

  @override
  _i4.Future<void> rejectWithdrawal(
    String? withdrawalId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectWithdrawal,
          [
            withdrawalId,
            reason,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i29.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> initiatePayment(
    String? orderId,
    double? amount,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiatePayment,
          [
            orderId,
            amount,
            userId,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i30.dummyValue<String>(
          this,
          Invocation.method(
            #initiatePayment,
            [
              orderId,
              amount,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Stream<List<_i7.PaymentModel>> getPaymentsForOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForOrder,
          [orderId],
        ),
        returnValue: _i4.Stream<List<_i7.PaymentModel>>.empty(),
      ) as _i4.Stream<List<_i7.PaymentModel>>);

  @override
  _i4.Stream<List<_i7.PaymentModel>> streamUserPayments(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamUserPayments,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i7.PaymentModel>>.empty(),
      ) as _i4.Stream<List<_i7.PaymentModel>>);

  @override
  _i4.Future<void> createPayment(_i7.PaymentModel? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPayment,
          [payment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> processPayment(String? paymentId) => (super.noSuchMethod(
        Invocation.method(
          #processPayment,
          [paymentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
